// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace {

constexpr char kLicense[] =
    R"(// Copyright 2026 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY clay_keywords_codegen
//
)";

struct Bucket {
  std::vector<size_t> keyword_indices;
};

struct HashTable {
  std::vector<int32_t> bucket_seeds;
  std::vector<int32_t> slots;
};

std::string Trim(const std::string& value) {
  const size_t first = value.find_first_not_of(" \t\r\n");
  if (first == std::string::npos) {
    return "";
  }
  const size_t last = value.find_last_not_of(" \t\r\n");
  return value.substr(first, last - first + 1);
}

uint32_t Hash(const std::string& value, uint32_t seed) {
  uint32_t hash = 2166136261u ^ seed;
  for (unsigned char character : value) {
    hash ^= character;
    hash *= 16777619u;
  }
  return hash;
}

bool ReadKeywords(const std::string& path, std::vector<std::string>* keywords) {
  std::ifstream input(path);
  if (!input) {
    std::cerr << "Failed to open input: " << path << std::endl;
    return false;
  }

  std::unordered_set<std::string> seen;
  std::string line;
  size_t line_number = 0;
  size_t string_pool_size = 0;
  while (std::getline(input, line)) {
    ++line_number;
    std::string keyword = Trim(line);
    if (keyword.empty() || keyword.compare(0, 2, "//") == 0) {
      continue;
    }
    if (!seen.insert(keyword).second) {
      std::cerr << path << ":" << line_number
                << ": duplicate keyword: " << keyword << std::endl;
      return false;
    }
    string_pool_size += keyword.size() + 1;
    if (string_pool_size >
        static_cast<size_t>(std::numeric_limits<uint16_t>::max()) + 1) {
      std::cerr << "Keyword string pool exceeds 16-bit offsets" << std::endl;
      return false;
    }
    keywords->push_back(std::move(keyword));
  }

  if (keywords->empty()) {
    std::cerr << "No keywords found in " << path << std::endl;
    return false;
  }
  if (keywords->size() >
      static_cast<size_t>(std::numeric_limits<int16_t>::max())) {
    std::cerr << "Too many keywords for KeywordID" << std::endl;
    return false;
  }
  return true;
}

bool BuildHashTable(const std::vector<std::string>& keywords,
                    HashTable* table) {
  const size_t table_size = keywords.size();
  std::vector<Bucket> buckets(table_size);
  for (size_t index = 0; index < table_size; ++index) {
    buckets[Hash(keywords[index], 0) % table_size].keyword_indices.push_back(
        index);
  }
  std::stable_sort(
      buckets.begin(), buckets.end(), [](const Bucket& lhs, const Bucket& rhs) {
        return lhs.keyword_indices.size() > rhs.keyword_indices.size();
      });

  table->bucket_seeds.assign(table_size, 0);
  table->slots.assign(table_size, -1);
  std::vector<bool> used(table_size, false);
  std::vector<size_t> singleton_buckets;

  for (const Bucket& bucket : buckets) {
    if (bucket.keyword_indices.size() <= 1) {
      if (bucket.keyword_indices.size() == 1) {
        singleton_buckets.push_back(
            Hash(keywords[bucket.keyword_indices[0]], 0) % table_size);
      }
      continue;
    }

    const size_t bucket_index =
        Hash(keywords[bucket.keyword_indices[0]], 0) % table_size;
    bool found_seed = false;
    for (uint32_t seed = 1;
         seed < static_cast<uint32_t>(std::numeric_limits<int32_t>::max());
         ++seed) {
      std::vector<size_t> candidate_slots;
      bool collision = false;
      for (size_t keyword_index : bucket.keyword_indices) {
        const size_t slot = Hash(keywords[keyword_index], seed) % table_size;
        if (used[slot] ||
            std::find(candidate_slots.begin(), candidate_slots.end(), slot) !=
                candidate_slots.end()) {
          collision = true;
          break;
        }
        candidate_slots.push_back(slot);
      }
      if (collision) {
        continue;
      }

      table->bucket_seeds[bucket_index] = static_cast<int32_t>(seed);
      for (size_t index = 0; index < candidate_slots.size(); ++index) {
        const size_t slot = candidate_slots[index];
        used[slot] = true;
        table->slots[slot] =
            static_cast<int32_t>(bucket.keyword_indices[index]);
      }
      found_seed = true;
      break;
    }
    if (!found_seed) {
      std::cerr << "Failed to build collision-free keyword table" << std::endl;
      return false;
    }
  }

  size_t free_slot = 0;
  for (size_t bucket_index : singleton_buckets) {
    while (free_slot < table_size && used[free_slot]) {
      ++free_slot;
    }
    if (free_slot == table_size) {
      std::cerr << "Failed to allocate singleton keyword slot" << std::endl;
      return false;
    }
    table->bucket_seeds[bucket_index] = -static_cast<int32_t>(free_slot) - 1;
    used[free_slot] = true;
  }

  for (size_t index = 0; index < table_size; ++index) {
    const size_t bucket_index = Hash(keywords[index], 0) % table_size;
    if (table->bucket_seeds[bucket_index] < 0) {
      const size_t slot =
          static_cast<size_t>(-table->bucket_seeds[bucket_index] - 1);
      table->slots[slot] = static_cast<int32_t>(index);
    }
  }
  return true;
}

bool VerifyHashTable(const std::vector<std::string>& keywords,
                     const HashTable& table) {
  const size_t table_size = keywords.size();
  for (size_t index = 0; index < table_size; ++index) {
    const std::string& keyword = keywords[index];
    const size_t bucket = Hash(keyword, 0) % table_size;
    const int32_t seed = table.bucket_seeds[bucket];
    const size_t slot =
        seed < 0 ? static_cast<size_t>(-seed - 1)
                 : Hash(keyword, static_cast<uint32_t>(seed)) % table_size;
    if (table.slots[slot] != static_cast<int32_t>(index)) {
      std::cerr << "Generated table failed to resolve keyword: " << keyword
                << std::endl;
      return false;
    }
  }
  return true;
}

bool WriteFile(const std::string& path, const std::string& contents) {
  std::ofstream output(path, std::ios::binary);
  if (!output) {
    std::cerr << "Failed to open output: " << path << std::endl;
    return false;
  }
  output << contents;
  if (!output) {
    std::cerr << "Failed to write output: " << path << std::endl;
    return false;
  }
  return true;
}

std::string GenerateSource(const std::vector<std::string>& keywords,
                           const HashTable& table) {
  std::vector<uint16_t> keyword_offsets;
  size_t keyword_offset = 0;
  for (const std::string& keyword : keywords) {
    if (keyword_offset >
        static_cast<size_t>(std::numeric_limits<uint16_t>::max())) {
      std::cerr << "Keyword string pool exceeds 16-bit offsets" << std::endl;
      return "";
    }
    keyword_offsets.push_back(static_cast<uint16_t>(keyword_offset));
    keyword_offset += keyword.size() + 1;
  }

  std::ostringstream output;
  output << kLicense << R"(
#include "clay/ui/component/keywords.h"

#include <cstddef>
#include <cstdint>
#include <string>

namespace clay {
namespace {

constexpr uint32_t Hash(const char* value, size_t length, uint32_t seed) {
  uint32_t hash = 2166136261u ^ seed;
  for (size_t index = 0; index < length; ++index) {
    hash ^= static_cast<unsigned char>(value[index]);
    hash *= 16777619u;
  }
  return hash;
}

constexpr int32_t kBucketSeeds[] = {
)";
  for (size_t index = 0; index < table.bucket_seeds.size(); ++index) {
    output << "  " << table.bucket_seeds[index]
           << (index + 1 == table.bucket_seeds.size() ? "\n" : ",\n");
  }
  output << R"(};

constexpr int16_t kSlots[] = {
)";
  for (size_t index = 0; index < table.slots.size(); ++index) {
    output << "  " << table.slots[index]
           << (index + 1 == table.slots.size() ? "\n" : ",\n");
  }
  output << R"(};

constexpr uint16_t kKeywordOffsets[] = {
)";
  for (size_t index = 0; index < keyword_offsets.size(); ++index) {
    output << "  " << keyword_offsets[index]
           << (index + 1 == keyword_offsets.size() ? "\n" : ",\n");
  }
  output << R"(};

constexpr char kKeywordStringPool[] =
)";
  for (const std::string& keyword : keywords) {
    output << "    \"" << keyword << "\\0\"\n";
  }
  output << R"(    ;

}  // namespace

KeywordID GetKeywordID(const std::string& str) {
  constexpr size_t kKeywordCount =
      sizeof(kKeywordOffsets) / sizeof(kKeywordOffsets[0]);
  const size_t bucket = Hash(str.data(), str.size(), 0) % kKeywordCount;
  const int32_t seed = kBucketSeeds[bucket];
  const size_t slot =
      seed < 0 ? static_cast<size_t>(-seed - 1)
               : Hash(str.data(), str.size(), static_cast<uint32_t>(seed)) %
                     kKeywordCount;
  const int16_t keyword_index = kSlots[slot];
  return keyword_index >= 0 &&
                 str == kKeywordStringPool + kKeywordOffsets[keyword_index]
             ? static_cast<KeywordID>(keyword_index)
             : KeywordID::kInvalid;
}

}  // namespace clay
)";
  return output.str();
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 3) {
    std::cerr << "Usage: " << argv[0] << " <keywords.in> <keywords.cc>"
              << std::endl;
    return 1;
  }

  std::vector<std::string> keywords;
  if (!ReadKeywords(argv[1], &keywords)) {
    return 1;
  }

  HashTable table;
  if (!BuildHashTable(keywords, &table) || !VerifyHashTable(keywords, table)) {
    return 1;
  }

  const std::string source = GenerateSource(keywords, table);
  if (source.empty()) {
    return 1;
  }

  return WriteFile(argv[2], source) ? 0 : 1;
}
